import { Room } from './Room';


export const  ROOMS: Room[] = [
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
    {name: 'penthouse',
    view: 'panoramica',
    capacity: 6,
    comodities: ['servicio a la habitacion', 'limpiesa', 'jacuzi', 'balcon']},
];
